# This is a basic workflow to help you get started with Actions
name: API CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy-api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build and publish docker image
        run: | 
          docker build -t docker.pkg.github.com/ffauchille/arla-group-11/arlaid-api:${{ github.sha }} api/Dockerfile
          docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push docker.pkg.github.com/ffauchille/arla-group-11/arlaid-api:${{ github.sha }}
      # Runs a set of commands using the runners shell
      - name: Deploy on production VM
        uses: appleboy/ssh-action@master
        env:
          TAG: ${{ github.sha }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: TAG
          script: |
            docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull docker.pkg.github.com/ffauchille/arla-group-11/arlaid-api:$TAG
            (docker stop arlaide-api && docker rm arlaide-api) || echo "Nothing to stop..."
            docker run -d --network web --name arlaide-api --label traefik.enable=true --label traefik.docker.network=web --label traefik.frontend.rule=Host:api.${{ secrets.SSH_HOST }} --label traefik.frontend.port=80 docker.pkg.github.com/ffauchille/arla-group-11/arlaid-api:$TAG